apiVersion: 1
datasources:
  - name: OpenSearch
    type: opensearch
    access: proxy
    url: http://opensearch:9200
    basicAuth: false
    isDefault: true
    jsonData:
      timeField: "@timestamp"
      tlsSkipVerify: true
      version: "2.15.0"
